name: Telegram Reminder

on:
  schedule:
    - cron: "30 11 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run reminder script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID_1: ${{ secrets.CHAT_ID_1 }}
          CHAT_ID_2: ${{ secrets.CHAT_ID_2 }}
        run: python reminder.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add reminder.csv
          git commit -m "Update reminder dates"
          git push
        continue-on-error: true
